# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_redirects', '0004_auto_20171208_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirecttranslation',
            name='redirect_type',
            field=models.IntegerField(choices=[(301, 'Permanent (301)'), (302, 'Temporary (302)')], default=302, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='staticredirect',
            name='redirect_type',
            field=models.IntegerField(choices=[(301, 'Permanent (301)'), (302, 'Temporary (302)')], default=302, verbose_name='type'),
        ),
    ]
