# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_redirects', '0005_auto_20181126_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aldryn_redirects.Redirect'),
        ),
        migrations.AddField(
            model_name='staticredirect',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aldryn_redirects.StaticRedirect'),
        ),
        migrations.AlterUniqueTogether(
            name='redirect',
            unique_together=set([]),
        ),
    ]
